package com.example.my_movie_app.api.models

data class FilmModel(
    val kinopoiskId: Int? = null,
    val filmId: Int? = null,
    val imdbId: String? = null,
    val nameRu: String? = null,
    val nameEn: String? = null,
    val nameOriginal: String? = null,
    val year: String? = null,
    val posterUrl: String? = null,
    val posterUrlPreview: String? = null,
    val coverUrl: String? = null,
    val logoUrl: String? = null,
    val countries: MutableList<CountryModel>? = null,
    val genres: MutableList<GenreModel>? = null,
    val reviewsCount: Int? = null,
    val ratingGoodReviewVoteCount: Int? = null,
    val ratingKinopoiskVoteCount: Int? = null,
    val ratingGoodReview: Double? = null,
    val ratingKinopoisk: Double? = null,
    val ratingImdb: Double? = null,
    val ratingImdbVoteCount: Int? = null,
    val ratingFilmCritics: Double? = null,
    val ratingFilmCriticsVoteCount: Int? = null,
    val ratingAwait: Double? = null,
    val ratingAwaitCount: Int? = null,
    val ratingRfCritics: Double? = null,
    val ratingRfCriticsVoteCount: Int? = null,
    val webUrl: String? = null,
    val filmLength: String? = null,
    val startYear: Int? = null,
    val endYear: Int? = null,
    val slogan: String? = null,
    val description: String? = null,
    val shortDescription: String? = null,
    val editorAnnotation: String? = null,
    val isTicketsAvailable: Boolean? = null,
    val productionStatus: String? = null,
    val type: String? = null,
    val ratingMpaa: String? = null,
    val ratingAgeLimits: String? = null,
    val hasImax: Boolean? = null,
    val has3D: Boolean? = null,
    val serial: Boolean? = null,
    val shortFilm: Boolean? = null,
    val completed: Boolean? = null,
    val lastSync: String? = null,
    val premiereRu: String? = null,
): Comparable<FilmModel> {
    override fun compareTo(other: FilmModel) = nameRu!!.compareTo(other.nameRu!!)
}
